using Documenter

include("preprocess.jl")

# download latest changelog
download("https://raw.githubusercontent.com/julia-vscode/julia-vscode/main/CHANGELOG.md", joinpath(@__DIR__, "src", "changelog.md"))
# download package.json so we can generate an overview over keybindings/commands/...
download("https://raw.githubusercontent.com/julia-vscode/julia-vscode/main/package.json", joinpath(@__DIR__, "src", "package.json"))

generate_keybindings()

makedocs(
    sitename = "Julia in VS Code",
    pages = [
        "Home" => "index.md",
        # "Setup" => "setup.md",
        "Getting Started" => "gettingstarted.md",
        "FAQ" => "faq.md",
        "User Guide" => Any[
            "Running Code"=>"userguide/runningcode.md",
            "Keybindings & Commands"=>"userguide/keybindings.md", # auto-generated by generate_keybindings
            "Julia Environments"=>"userguide/env.md",
            "Code Navigation"=>"userguide/codenavigation.md",
            "Editing Code"=>"userguide/editingcode.md",
            "Formatting Code"=>"userguide/formatter.md",
            "Plots"=>"userguide/plotgallery.md",
            "Table Viewer"=>"userguide/grid.md",
            # "Understanding Code" => "userguide/understandingcode.md",
            "Linter"=>"userguide/linter.md",
            "Profiler"=>"userguide/profiler.md",
            # "Tasks" => "userguide/tasks.md",
            "Debugging"=>"userguide/debugging.md",
            "Compiling Sysimages"=>"userguide/compilesysimage.md",
            "Julia Markdown Documents"=>"userguide/weave.md",
            "Remote Development"=>"userguide/remote.md",
            "Test Item Framework"=>"userguide/testitems.md"
            # "Settings" => "userguide/settings.md"
        ],
        "Change Log" => "changelog.md",
        "Developer Documentation" => Any[
            "Overview"=>"devdocs/devdocs.md"
        ]
    ],
    format = Documenter.HTML(
        prettyurls = ("CI" in keys(ENV))
    )
)

deploydocs(
    repo = "github.com/julia-vscode/docs";
    push_preview = true
)
